workflows:
  android-release:
    name: Android Release APK
    max_build_duration: 60
    environment:
      node: 18.18.0
      java: 17
      vars:
        PACKAGE_NAME: "com.otaappwork"
    scripts:
      - name: Install dependencies
        script: npm install

      - name: Bundle JS for Android
        script: |
          npx react-native bundle \
            --platform android \
            --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res/

      - name: Build Android APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/apk/release/*.apk

    publishing:
      email:
        recipients:
          - kevin@bluestoneapps.com
        notify:
          success: true
          failure: true
