/**
 * Curated grocery food list for Smart Suggestions.
 * Based on the Gas Tank spreadsheet — common, affordable Walmart grocery items.
 * Nutrition values are per 100g (USDA standard).
 * portionGrams = one standard grocery purchase unit.
 * storePrice = typical Walmart price per unit (updated regularly).
 *
 * Nutrient keys must match nutrients.js exactly (incl. MAGNEISUM/POTASIUM typos).
 */
export const CURATED_GROCERY_FOODS = [
  // ─── PROTEIN SOURCES ────────────────────────────────────────
  {
    fdcId: 'g_pinto_beans',
    description: 'Pinto beans',
    portionGrams: 439,   // one 15.5oz can
    storePrice: 0.98,
    allNutrients: {
      PROTEIN:  { amount: 8.9 },
      CARBS:    { amount: 26.2 },
      FAT:      { amount: 0.5 },
      FIBER:    { amount: 9.0 },
      CALCIUM:  { amount: 55 },
      IRON:     { amount: 2.2 },
      MAGNEISUM:{ amount: 50 },
      ZINC:     { amount: 1.1 },
      POTASIUM: { amount: 436 },
      SODIUM:   { amount: 180 },
      FOLATE:   { amount: 172 },
      'VIT B6': { amount: 0.26 },
    },
  },
  {
    fdcId: 'g_kidney_beans',
    description: 'Kidney beans',
    portionGrams: 439,   // one 15.5oz can
    storePrice: 0.98,
    allNutrients: {
      PROTEIN:  { amount: 8.7 },
      CARBS:    { amount: 22.8 },
      FAT:      { amount: 0.5 },
      FIBER:    { amount: 6.4 },
      CALCIUM:  { amount: 43 },
      IRON:     { amount: 2.9 },
      MAGNEISUM:{ amount: 45 },
      ZINC:     { amount: 1.1 },
      POTASIUM: { amount: 340 },
      SODIUM:   { amount: 220 },
      FOLATE:   { amount: 130 },
      'VIT B6': { amount: 0.21 },
    },
  },
  {
    fdcId: 'g_chickpeas',
    description: 'Chickpeas',
    portionGrams: 439,   // one 15.5oz can
    storePrice: 1.28,
    allNutrients: {
      PROTEIN:  { amount: 8.9 },
      CARBS:    { amount: 27.4 },
      FAT:      { amount: 2.6 },
      FIBER:    { amount: 7.6 },
      CALCIUM:  { amount: 49 },
      IRON:     { amount: 2.9 },
      MAGNEISUM:{ amount: 48 },
      ZINC:     { amount: 1.5 },
      POTASIUM: { amount: 291 },
      SODIUM:   { amount: 240 },
      FOLATE:   { amount: 172 },
      'VIT B6': { amount: 0.13 },
    },
  },
  {
    fdcId: 'g_lentils',
    description: 'Lentils dry',
    portionGrams: 454,   // 1lb bag
    storePrice: 2.48,
    allNutrients: {
      PROTEIN:  { amount: 25.8 },
      CARBS:    { amount: 60.1 },
      FAT:      { amount: 1.1 },
      FIBER:    { amount: 10.7 },
      CALCIUM:  { amount: 56 },
      IRON:     { amount: 7.5 },
      MAGNEISUM:{ amount: 122 },
      ZINC:     { amount: 3.3 },
      POTASIUM: { amount: 677 },
      SODIUM:   { amount: 6 },
      FOLATE:   { amount: 479 },
      'VIT B6': { amount: 0.54 },
      'VIT B12':{ amount: 0 },
    },
  },
  {
    fdcId: 'g_peanuts',
    description: 'Peanuts',
    portionGrams: 454,   // 16oz jar
    storePrice: 3.98,
    allNutrients: {
      PROTEIN:  { amount: 25.8 },
      CARBS:    { amount: 16.1 },
      FAT:      { amount: 49.2 },
      FIBER:    { amount: 8.5 },
      CALCIUM:  { amount: 92 },
      IRON:     { amount: 4.6 },
      MAGNEISUM:{ amount: 168 },
      ZINC:     { amount: 3.3 },
      POTASIUM: { amount: 705 },
      SODIUM:   { amount: 18 },
      FOLATE:   { amount: 240 },
      'VIT B6': { amount: 0.35 },
      'VIT E':  { amount: 8.3 },
    },
  },
  {
    fdcId: 'g_eggs',
    description: 'Eggs large',
    portionGrams: 600,   // one dozen (~50g each × 12)
    storePrice: 3.98,
    allNutrients: {
      PROTEIN:  { amount: 12.6 },
      FAT:      { amount: 10.6 },
      CALCIUM:  { amount: 56 },
      IRON:     { amount: 1.8 },
      MAGNEISUM:{ amount: 12 },
      ZINC:     { amount: 1.3 },
      POTASIUM: { amount: 138 },
      SODIUM:   { amount: 142 },
      'VIT A':  { amount: 149 },
      'VIT D':  { amount: 2.0 },
      'VIT E':  { amount: 1.0 },
      'VIT B6': { amount: 0.17 },
      'VIT B12':{ amount: 1.11 },
      FOLATE:   { amount: 47 },
    },
  },
  {
    fdcId: 'g_chicken_legs',
    description: 'Chicken leg quarters',
    portionGrams: 1587,  // ~3.5lb family pack
    storePrice: 4.37,
    allNutrients: {
      PROTEIN:  { amount: 22.0 },
      FAT:      { amount: 15.3 },
      CALCIUM:  { amount: 12 },
      IRON:     { amount: 1.2 },
      MAGNEISUM:{ amount: 22 },
      ZINC:     { amount: 2.1 },
      POTASIUM: { amount: 220 },
      SODIUM:   { amount: 82 },
      'VIT B6': { amount: 0.4 },
      'VIT B12':{ amount: 0.3 },
      'VIT D':  { amount: 0.3 },
    },
  },
  {
    fdcId: 'g_whole_turkey',
    description: 'Whole turkey',
    portionGrams: 5443,  // 12lb frozen
    storePrice: 14.28,
    allNutrients: {
      PROTEIN:  { amount: 20.6 },
      FAT:      { amount: 7.4 },
      CALCIUM:  { amount: 13 },
      IRON:     { amount: 1.5 },
      MAGNEISUM:{ amount: 24 },
      ZINC:     { amount: 2.0 },
      POTASIUM: { amount: 298 },
      SODIUM:   { amount: 70 },
      'VIT B6': { amount: 0.63 },
      'VIT B12':{ amount: 0.3 },
      'VIT D':  { amount: 0.1 },
    },
  },
  // ─── DAIRY / CALCIUM ────────────────────────────────────────
  {
    fdcId: 'g_chocolate_milk',
    description: 'Chocolate milk',
    portionGrams: 1893,  // half gallon
    storePrice: 3.48,
    allNutrients: {
      PROTEIN:  { amount: 3.4 },
      CARBS:    { amount: 10.2 },
      FAT:      { amount: 1.0 },
      CALCIUM:  { amount: 129 },
      IRON:     { amount: 0.23 },
      MAGNEISUM:{ amount: 13 },
      ZINC:     { amount: 0.43 },
      POTASIUM: { amount: 172 },
      SODIUM:   { amount: 65 },
      'VIT A':  { amount: 46 },
      'VIT D':  { amount: 2.9 },
      'VIT B12':{ amount: 1.0 },
    },
  },
  {
    fdcId: 'g_american_cheese',
    description: 'American cheese slices',
    portionGrams: 340,   // 12oz pack
    storePrice: 3.98,
    allNutrients: {
      PROTEIN:  { amount: 16.0 },
      FAT:      { amount: 27.0 },
      CALCIUM:  { amount: 850 },
      IRON:     { amount: 0.4 },
      MAGNEISUM:{ amount: 20 },
      ZINC:     { amount: 2.8 },
      POTASIUM: { amount: 217 },
      SODIUM:   { amount: 1441 },
      'VIT A':  { amount: 360 },
      'VIT D':  { amount: 0.5 },
      'VIT B12':{ amount: 0.8 },
    },
  },
  {
    fdcId: 'g_whole_milk',
    description: 'Whole milk',
    portionGrams: 3785,  // 1 gallon
    storePrice: 3.98,
    allNutrients: {
      PROTEIN:  { amount: 3.2 },
      FAT:      { amount: 3.3 },
      CARBS:    { amount: 4.8 },
      CALCIUM:  { amount: 113 },
      IRON:     { amount: 0.03 },
      MAGNEISUM:{ amount: 10 },
      ZINC:     { amount: 0.37 },
      POTASIUM: { amount: 132 },
      SODIUM:   { amount: 44 },
      'VIT A':  { amount: 46 },
      'VIT D':  { amount: 3.2 },
      'VIT B12':{ amount: 0.45 },
      'VIT B6': { amount: 0.04 },
    },
  },
  // ─── VEGETABLES / VITAMINS ──────────────────────────────────
  {
    fdcId: 'g_carrots',
    description: 'Carrots baby cut',
    portionGrams: 454,   // 1lb bag
    storePrice: 1.48,
    allNutrients: {
      PROTEIN:  { amount: 0.9 },
      CARBS:    { amount: 9.6 },
      FIBER:    { amount: 2.8 },
      CALCIUM:  { amount: 33 },
      IRON:     { amount: 0.30 },
      MAGNEISUM:{ amount: 12 },
      ZINC:     { amount: 0.24 },
      POTASIUM: { amount: 320 },
      SODIUM:   { amount: 69 },
      'VIT A':  { amount: 835 },
      'VIT C':  { amount: 5.9 },
      'VIT K':  { amount: 13.2 },
      'VIT B6': { amount: 0.14 },
      FOLATE:   { amount: 19 },
    },
  },
  {
    fdcId: 'g_sweet_potatoes',
    description: 'Sweet potatoes',
    portionGrams: 1360,  // 3lb bag
    storePrice: 3.98,
    allNutrients: {
      PROTEIN:  { amount: 1.6 },
      CARBS:    { amount: 20.1 },
      FIBER:    { amount: 3.0 },
      CALCIUM:  { amount: 30 },
      IRON:     { amount: 0.61 },
      MAGNEISUM:{ amount: 25 },
      ZINC:     { amount: 0.30 },
      POTASIUM: { amount: 337 },
      SODIUM:   { amount: 55 },
      'VIT A':  { amount: 961 },
      'VIT C':  { amount: 19.6 },
      'VIT K':  { amount: 1.8 },
      'VIT B6': { amount: 0.28 },
      'VIT E':  { amount: 0.26 },
      FOLATE:   { amount: 11 },
    },
  },
  {
    fdcId: 'g_frozen_spinach',
    description: 'Frozen spinach',
    portionGrams: 283,   // 10oz bag
    storePrice: 1.48,
    allNutrients: {
      PROTEIN:  { amount: 2.97 },
      CARBS:    { amount: 3.63 },
      FIBER:    { amount: 2.4 },
      CALCIUM:  { amount: 136 },
      IRON:     { amount: 3.57 },
      MAGNEISUM:{ amount: 79 },
      ZINC:     { amount: 0.76 },
      POTASIUM: { amount: 466 },
      SODIUM:   { amount: 99 },
      'VIT A':  { amount: 524 },
      'VIT C':  { amount: 10.4 },
      'VIT K':  { amount: 540 },
      'VIT B6': { amount: 0.24 },
      FOLATE:   { amount: 145 },
      'VIT E':  { amount: 2.08 },
    },
  },
  {
    fdcId: 'g_frozen_broccoli',
    description: 'Frozen broccoli',
    portionGrams: 340,   // 12oz bag
    storePrice: 1.98,
    allNutrients: {
      PROTEIN:  { amount: 2.8 },
      CARBS:    { amount: 6.6 },
      FIBER:    { amount: 2.6 },
      CALCIUM:  { amount: 47 },
      IRON:     { amount: 0.73 },
      MAGNEISUM:{ amount: 21 },
      ZINC:     { amount: 0.41 },
      POTASIUM: { amount: 293 },
      SODIUM:   { amount: 41 },
      'VIT A':  { amount: 31 },
      'VIT C':  { amount: 64 },
      'VIT K':  { amount: 92 },
      'VIT B6': { amount: 0.20 },
      FOLATE:   { amount: 63 },
      'VIT E':  { amount: 0.78 },
    },
  },
  {
    fdcId: 'g_russet_potatoes',
    description: 'Russet potatoes',
    portionGrams: 2268,  // 5lb bag
    storePrice: 4.78,
    allNutrients: {
      PROTEIN:  { amount: 2.5 },
      CARBS:    { amount: 17.5 },
      FIBER:    { amount: 2.1 },
      CALCIUM:  { amount: 12 },
      IRON:     { amount: 0.78 },
      MAGNEISUM:{ amount: 23 },
      ZINC:     { amount: 0.36 },
      POTASIUM: { amount: 425 },
      SODIUM:   { amount: 6 },
      'VIT C':  { amount: 19.7 },
      'VIT B6': { amount: 0.30 },
      FOLATE:   { amount: 15 },
      'VIT B12':{ amount: 0 },
    },
  },
  {
    fdcId: 'g_bananas',
    description: 'Bananas',
    portionGrams: 454,   // ~1lb bunch
    storePrice: 1.28,
    allNutrients: {
      PROTEIN:  { amount: 1.09 },
      CARBS:    { amount: 22.84 },
      FIBER:    { amount: 2.6 },
      CALCIUM:  { amount: 5 },
      IRON:     { amount: 0.26 },
      MAGNEISUM:{ amount: 27 },
      ZINC:     { amount: 0.15 },
      POTASIUM: { amount: 358 },
      SODIUM:   { amount: 1 },
      'VIT C':  { amount: 8.7 },
      'VIT B6': { amount: 0.37 },
      FOLATE:   { amount: 20 },
    },
  },
  {
    fdcId: 'g_oranges',
    description: 'Navel oranges',
    portionGrams: 1814,  // 4lb bag
    storePrice: 5.48,
    allNutrients: {
      PROTEIN:  { amount: 0.94 },
      CARBS:    { amount: 11.75 },
      FIBER:    { amount: 2.4 },
      CALCIUM:  { amount: 40 },
      IRON:     { amount: 0.10 },
      MAGNEISUM:{ amount: 10 },
      ZINC:     { amount: 0.06 },
      POTASIUM: { amount: 181 },
      SODIUM:   { amount: 0 },
      'VIT C':  { amount: 59 },
      'VIT A':  { amount: 11 },
      'VIT B6': { amount: 0.06 },
      FOLATE:   { amount: 30 },
    },
  },
  {
    fdcId: 'g_sunflower_seeds',
    description: 'Sunflower seeds dry roasted',
    portionGrams: 340,   // 12oz bag
    storePrice: 4.98,
    allNutrients: {
      PROTEIN:  { amount: 20.8 },
      FAT:      { amount: 51.5 },
      CARBS:    { amount: 18.6 },
      FIBER:    { amount: 8.6 },
      CALCIUM:  { amount: 78 },
      IRON:     { amount: 3.8 },
      MAGNEISUM:{ amount: 325 },
      ZINC:     { amount: 5.3 },
      POTASIUM: { amount: 645 },
      SODIUM:   { amount: 3 },
      FOLATE:   { amount: 227 },
      'VIT E':  { amount: 35.2 },
      'VIT B6': { amount: 0.77 },
      'VIT B12':{ amount: 0 },
    },
  },
  // ─── GRAINS / CARBS ─────────────────────────────────────────
  {
    fdcId: 'g_white_rice',
    description: 'White rice long grain enriched',
    portionGrams: 907,   // 2lb bag
    storePrice: 1.98,
    allNutrients: {
      PROTEIN:  { amount: 6.6 },
      CARBS:    { amount: 80.0 },
      FAT:      { amount: 0.58 },
      FIBER:    { amount: 1.4 },
      CALCIUM:  { amount: 28 },
      IRON:     { amount: 1.5 },
      MAGNEISUM:{ amount: 25 },
      ZINC:     { amount: 1.1 },
      POTASIUM: { amount: 115 },
      SODIUM:   { amount: 5 },
      FOLATE:   { amount: 466 },
      'VIT B6': { amount: 0.12 },
    },
  },
  {
    fdcId: 'g_brown_rice',
    description: 'Brown rice',
    portionGrams: 907,   // 2lb bag
    storePrice: 2.28,
    allNutrients: {
      PROTEIN:  { amount: 7.5 },
      CARBS:    { amount: 77.2 },
      FAT:      { amount: 2.7 },
      FIBER:    { amount: 3.5 },
      CALCIUM:  { amount: 33 },
      IRON:     { amount: 1.5 },
      MAGNEISUM:{ amount: 143 },
      ZINC:     { amount: 2.0 },
      POTASIUM: { amount: 223 },
      SODIUM:   { amount: 7 },
      FOLATE:   { amount: 9 },
      'VIT B6': { amount: 0.51 },
    },
  },
  {
    fdcId: 'g_oats',
    description: 'Rolled oats',
    portionGrams: 1190,  // 42oz canister
    storePrice: 3.28,
    allNutrients: {
      PROTEIN:  { amount: 13.2 },
      CARBS:    { amount: 67.7 },
      FAT:      { amount: 6.9 },
      FIBER:    { amount: 10.1 },
      CALCIUM:  { amount: 54 },
      IRON:     { amount: 4.7 },
      MAGNEISUM:{ amount: 177 },
      ZINC:     { amount: 3.6 },
      POTASIUM: { amount: 429 },
      SODIUM:   { amount: 2 },
      FOLATE:   { amount: 56 },
      'VIT B6': { amount: 0.12 },
      'VIT E':  { amount: 0.42 },
    },
  },
  {
    fdcId: 'g_whole_wheat_bread',
    description: 'Whole wheat bread',
    portionGrams: 567,   // 20oz loaf
    storePrice: 2.98,
    allNutrients: {
      PROTEIN:  { amount: 9.7 },
      CARBS:    { amount: 43.1 },
      FAT:      { amount: 3.6 },
      FIBER:    { amount: 7.4 },
      CALCIUM:  { amount: 107 },
      IRON:     { amount: 2.9 },
      MAGNEISUM:{ amount: 76 },
      ZINC:     { amount: 1.8 },
      POTASIUM: { amount: 248 },
      SODIUM:   { amount: 406 },
      FOLATE:   { amount: 111 },
      'VIT B6': { amount: 0.18 },
      'VIT B12':{ amount: 0 },
    },
  },
  {
    fdcId: 'g_canned_tuna',
    description: 'Canned tuna in water',
    portionGrams: 142,   // 5oz can
    storePrice: 1.48,
    allNutrients: {
      PROTEIN:  { amount: 26.0 },
      FAT:      { amount: 0.82 },
      CALCIUM:  { amount: 11 },
      IRON:     { amount: 1.3 },
      MAGNEISUM:{ amount: 31 },
      ZINC:     { amount: 0.9 },
      POTASIUM: { amount: 207 },
      SODIUM:   { amount: 396 },
      'VIT D':  { amount: 4.0 },
      'VIT B6': { amount: 0.45 },
      'VIT B12':{ amount: 2.5 },
    },
  },
  {
    fdcId: 'g_canned_salmon',
    description: 'Canned salmon',
    portionGrams: 213,   // 7.5oz can
    storePrice: 3.48,
    allNutrients: {
      PROTEIN:  { amount: 24.6 },
      FAT:      { amount: 6.6 },
      CALCIUM:  { amount: 232 },
      IRON:     { amount: 0.96 },
      MAGNEISUM:{ amount: 32 },
      ZINC:     { amount: 0.76 },
      POTASIUM: { amount: 369 },
      SODIUM:   { amount: 443 },
      'VIT D':  { amount: 11.0 },
      'VIT B6': { amount: 0.58 },
      'VIT B12':{ amount: 3.2 },
    },
  },
  {
    fdcId: 'g_oats',
    description: 'Old fashioned oats',
    portionGrams: 1190,  // 42oz canister
    storePrice: 3.28,
    allNutrients: {
      PROTEIN:  { amount: 13.2 },
      CARBS:    { amount: 67.7 },
      FAT:      { amount: 6.9 },
      FIBER:    { amount: 10.1 },
      CALCIUM:  { amount: 54 },
      IRON:     { amount: 4.7 },
      MAGNEISUM:{ amount: 177 },
      ZINC:     { amount: 3.6 },
      POTASIUM: { amount: 429 },
      SODIUM:   { amount: 2 },
      FOLATE:   { amount: 56 },
      'VIT B6': { amount: 0.12 },
      'VIT E':  { amount: 0.42 },
    },
  },
  {
    fdcId: 'g_soybeans',
    description: 'Frozen edamame soybeans',
    portionGrams: 454,   // 1lb bag
    storePrice: 2.98,
    allNutrients: {
      PROTEIN:  { amount: 11.0 },
      CARBS:    { amount: 7.6 },
      FAT:      { amount: 4.7 },
      FIBER:    { amount: 4.2 },
      CALCIUM:  { amount: 63 },
      IRON:     { amount: 1.8 },
      MAGNEISUM:{ amount: 55 },
      ZINC:     { amount: 1.4 },
      POTASIUM: { amount: 436 },
      SODIUM:   { amount: 6 },
      FOLATE:   { amount: 311 },
      'VIT C':  { amount: 6.1 },
      'VIT K':  { amount: 31.4 },
      'VIT B6': { amount: 0.10 },
    },
  },
  {
    fdcId: 'g_fortified_cereal',
    description: 'Breakfast cereal fortified',
    portionGrams: 397,   // 14oz box
    storePrice: 2.98,
    allNutrients: {
      PROTEIN:  { amount: 7.0 },
      CARBS:    { amount: 83.0 },
      FIBER:    { amount: 10.0 },
      IRON:     { amount: 24.0 },   // heavily fortified
      CALCIUM:  { amount: 333 },
      ZINC:     { amount: 10.0 },
      FOLATE:   { amount: 667 },
      'VIT D':  { amount: 8.3 },
      'VIT B12':{ amount: 5.0 },
      'VIT A':  { amount: 500 },
      'VIT C':  { amount: 60 },
      'VIT B6': { amount: 1.7 },
      MAGNEISUM:{ amount: 67 },
      POTASIUM: { amount: 233 },
    },
  },
];
